
title: "Neo4j (r)elate"
description: "A framework of tools, services and libraries for working with Neo4j."
repository: "https://github.com/neo4j-devtools/relate"
twitter_username: neo4j
github_username:  neo4j

google_analytics: UA-1192232-34

permalink: pretty

defaults:  
  - scope:
      path: ""
    values:
      layout: "page"

exclude:  
  - "*.config.js"
  - "package*.json"
  - "node_modules"

kramdown:
  input: GFM
